trudyagi/accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy, reverse

from . import views

app_name = 'accounts'

urlpatterns = [
    path('registration/', views.RegisterView.as_view(), name="register"),
    path('login/', views.LoginUserView.as_view(), name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('change_email/', views.change_email, name="change_email"),
    path('change_contact_email/', views.change_contact_email, name="change_contact_email"),
    path('change_password/', PasswordChangeView.as_view(template_name='accounts/change_password.html', success_url=reverse_lazy('posts:index')), name="change_password"),
    path('profile/<str:username>', views.profile_view, name='profile'),
    path('activation/user_key/<str:sign>', views.activation_user_view, name='activation_page'),
    path('activation/warning/<str:sign>', views.activation_warning_view, name='activation_warning'),
    path('activation/resend_activation/<str:sign>', views.resend_activation, name='resend_activation')
]

trudyagi/cart/urls.py
from django.urls import path, include
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('cart_add/<uuid:product_id>', views.cart_add, name='cart_add'),
    path('create_order/', views.send_order, name='create_order'),
    path('requests_to_order/', views.requests_to_order, name='requests_to_order'),
]

trudyagi/trudyagi/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls', namespace='chat')),
    path('', include('posts.urls', namespace='posts')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('silk/', include('silk.urls', namespace='silk')),
    path('cart/', include('cart.urls', namespace='cart')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    path('static/', serve, {'document_root': settings.STATIC_ROOT})
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'trudyagi.views.handler404'
handler403 = 'trudyagi.views.handler403'
handler500 = 'trudyagi.views.handler500'

trudyagi/cart/models.py
from django.db import models
from posts.models import Product
from accounts.models import User

class Order(models.Model):
    author = models.ForeignKey(User, on_delete=models.PROTECT, related_name='author_orders', verbose_name='Отправитель')
    seller = models.ForeignKey(User, on_delete=models.PROTECT, related_name='seller_orders', verbose_name='Продавец')
    product = models.ForeignKey(Product, on_delete=models.PROTECT, related_name='product_orders', verbose_name='Продукт')
    first_name = models.CharField(max_length=50, verbose_name='Имя')
    last_name = models.CharField(max_length=50, verbose_name='Фамилия')
    country = models.CharField(max_length=200, verbose_name='Страна')
    city = models.CharField(max_length=200, verbose_name='Город')
    address = models.CharField(max_length=200, verbose_name='Адрес')
    postal_code = models.CharField(max_length=20, verbose_name='Почтовый индекс')
    additional_information = models.TextField(null=True, blank=True, verbose_name='Дополнительная информация')
    read = models.BooleanField(default=False, verbose_name='Прочитано')
    created = models.DateTimeField(auto_now_add=True)
    quantity = models.IntegerField(verbose_name='Количество')
    total_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Полная Цена')

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

trudyagi/cart/forms.py
from django import forms
from .models import Order

class ProductAddInCartFrom(forms.Form):
    PRODUCT_QUANTITY_CHOICE = [(i,str(i)) for i in range(1,21)]
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICE, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ['author', 'seller', 'product', 'quantity', 'total_price', 'read', 'created']

trudyagi/cart/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.views.decorators.http import require_POST
from django.shortcuts import get_object_or_404
from posts.models import Product
from .cart import Cart
from .forms import ProductAddInCartFrom, OrderForm
from django.http import HttpResponseRedirect
from django.shortcuts import reverse
from django.conf import settings
from .models import Order
from django.shortcuts import redirect

def cart(request):
    cart = Cart(request)
    return render(request,'cart/index.html', {'cart':cart})

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = ProductAddInCartFrom(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        print(cd.get('quantity', 1))
        cart.add(product=product,
                 quantity=cd.get('quantity', 1),
                 update_quantity=cd['update'])

    return HttpResponseRedirect(product.get_absolute_url())

def cart_remove(request, product_id):
    product = get_object_or_404(Product ,pk=product_id)
    cart = Cart(request)
    cart.remove(product)
    return HttpResponseRedirect(reverse('posts:product_detail', args=[product.id]))

@login_required
def send_order(request):
    cart = Cart(request)
    form = OrderForm()
    if request.method == 'POST':
        order_form = OrderForm(request.POST)
        if order_form.is_valid():
            for order_item in cart:
                order = order_form.save(commit=False)
                order.author = request.user
                order.seller = order_item['product'].author
                order.product = order_item['product']
                order.quantity = order_item['quantity']
                order.total_price = order_item['total_price']
                order.save()
            return redirect('posts:index')
    else:
        return render(request, 'cart/create_order.html', {'cart':cart, 'form':form})

@login_required
def requests_to_order(request):
    if request.user:
        orders = Order.objects.filter(seller=request.user)

    return render(request, 'cart/orders_messages.html', {'orders':orders})

trudyagi/cart/templates/cart/create_order.html
{% extends 'base_detail.html' %}

{% block content %}
<section class="section">
    <div class="name_section">
        <h2>Регистрация заказа</h2>
    </div>
    <div class="section_content">
        <div class="cart_content_conteiner">
            <div class="left_direction">
                <div class="products_conteiner">
                    {% for product in cart %}
                    <div class="product_cart_icon">
                        <div class="product_cart_icon__content">
                            <a href="">
                                <div class="product_image_place">
                                    <img class="convenient_picture" src="{{ product.product.image.url }}">
                                </div>
                                <div class="product_icon_name">
                                    <span>{{ product.product.name }}</span>
                                </div>
                            </a>
                            <div class="product_icon_price">
                                <p>Количество: {{ product.quantity }}</p>
                                <b>Общая цена: {{ product.total_price }}$</b>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="right_direction">
                <div class="white_back_block">
                    <div class="create_order_form">
                        <form method="post">
                            {% csrf_token %}
                            {% for item in form %}
                            <label>{{ item.label }}</label><br>
                            {{ item }}<br>
                            {% endfor %}
                            <button id="register_btn">Отправить заказ</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

trudyagi/cart/templates/cart/index.html
{% extends 'base_detail.html' %}

{% block content %}
<section class="section">
    <div class="name_section">
        <h2>Корзина</h2>
    </div>
    <div class="section_content">
        <div class="cart_content_conteiner">
            <div class="left_direction">
                <div class="products_conteiner">
                    {% for product in cart %}
                    <div class="product_cart_icon">
                        <div class="product_cart_icon__content">
                            <a href="">
                                <div class="product_image_place">
                                    <img class="convenient_picture" src="{{ product.product.image.url }}">
                                </div>
                                <div class="product_icon_name">
                                    <span>{{ product.product.name }}</span>
                                </div>
                            </a>
                            <div class="product_icon_price">
                                <p>Количество: {{ product.quantity }}</p>
                                <b>Общая цена: {{ product.total_price }}$</b>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="right_direction">
                <div class="white_back_block">
                    <div class="total_cart_conteiner">
                        <div class="total_cart_info">
                            <div class="total_products_info">
                                <div class="total_cart_option">
                                    <div class="name_option">
                                        <p>Количество продуктов:</p>
                                    </div>
                                    <div class="value_option">
                                        <b>{{ cart.get_total_quantity }}</b>
                                    </div>
                                </div>
                                <hr>
                                <div class="total_cart_price">
                                    <h2>Итог: {{ cart.get_total_price }}$</h2>
                                </div>
                            </div>
                        </div>
                        <div class="send_application_conteiner">
                            <a href="{% url 'cart:create_order' %}" class="blue_btn" id="send_purchase_request">
                                Отправить заявку
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

trudyagi/cart/templates/cart/orders_messages.html
{% extends 'base_detail.html' %}
{% load static %}

{% block content %}
<section class="section">
    <div class="name_section">
        <h2>Запросы на заказ</h2>
    </div>
    <div class="section_content">
        <div class="cart_content_conteiner">
            <div class="left_direction">
                <div class="products_conteiner">
                    {% for product in orders %}
                    <div class="product_cart_icon">
                        <div class="product_cart_icon__content">
                            <a href="">
                                <div class="product_image_place">
                                    <img class="convenient_picture" src="{{ product.product.image.url }}">
                                </div>
                                <div class="product_icon_name">
                                    <span>{{ product.product.name }}</span>
                                </div>
                            </a>
                            <div class="product_icon_order_info">
                                <div class="order_author_link">
                                    <a href="{% url 'accounts:profile' user.username %}">
                                        <div style="height: 30px;
                            width: 30px;background:url(
                            {% if user.icon %}
                                {{ product.author.icon.url }}
                            {% else%}
                                {% static 'posts/img/user-icon.png' %}
                            {% endif %}) center;
                            background-size: 100%;" class="profile_image"></div>
                                        <span>
                                            {{ product.author.username }}
                                        </span>
                                    </a>
                                </div>
                                <p>Имя: {{ product.first_name }} {{ product.last_name }}</p>
                                <p>
                                    Адрес: {{ product.country }}, {{ product.city }},
                                    {{ product.address }}, {{ product.postal_code }}
                                </p>
                                <p>Количество: {{ product.quantity }}</p>
                                <p>Количество: {{ product.quantity }}</p>
                                <b>Общая цена: {{ product.total_price }}$</b>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}