trudyagi/accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy, reverse

from . import views

app_name = 'accounts'

urlpatterns = [
    path('registration/', views.RegisterView.as_view(), name="register"),
    path('login/', views.LoginUserView.as_view(), name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('change_email/', views.change_email, name="change_email"),
    path('change_contact_email/', views.change_contact_email, name="change_contact_email"),
    path('change_password/', PasswordChangeView.as_view(template_name='accounts/change_password.html', success_url=reverse_lazy('posts:index')), name="change_password"),
    path('profile/<str:username>', views.profile_view, name='profile'),
    path('activation/user_key/<str:sign>', views.activation_user_view, name='activation_page'),
    path('activation/warning/<str:sign>', views.activation_warning_view, name='activation_warning'),
    path('activation/resend_activation/<str:sign>', views.resend_activation, name='resend_activation')
]

trudyagi/cart/urls.py
from django.urls import path, include
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('cart_add/<uuid:product_id>', views.cart_add, name='cart_add'),
    path('create_order/', views.send_order, name='create_order'),
    path('requests_to_order/', views.requests_to_order, name='requests_to_order'),
]

trudyagi/chat/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.index, name="index"),
    path('<str:room_name>/', views.room, name="room"),
]

trudyagi/posts/urls.py
from django.urls import path, include
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('rubrics/<slug:rubric_slug>', views.get_by_rubric, name='rubrics'),
    path('product/<uuid:product_unique_id>', views.product, name='product_detail'),
    path('add_product/', views.CreateProductView.as_view(), name='add-product'),
    path('search-product-data/', views.search_product_data, name='search_product_data'),
    path('search/<slug:category_slug>/<str:product_name>/', views.search_product_page, name='search_product_page'),
    path('home_search/', views.search_product_home, name='home_search'),
    path('delete-review/<int:review_id>', views.delete_review, name='delete_review'),
    path('delete-product/<uuid:pk>', views.DeleteProductView.as_view(), name='delete_product'),
    path('update-product/<uuid:pk>', views.UpdateProductView.as_view(), name='update_product'),
]

trudyagi/trudyagi/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls', namespace='chat')),
    path('', include('posts.urls', namespace='posts')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('silk/', include('silk.urls', namespace='silk')),
    path('cart/', include('cart.urls', namespace='cart')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    path('static/', serve, {'document_root': settings.STATIC_ROOT})
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'trudyagi.views.handler404'
handler403 = 'trudyagi.views.handler403'
handler500 = 'trudyagi.views.handler500'

trudyagi/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width">
    <title>Title</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Staatliches&family=Ubuntu:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet"  type="text/css" href="{% static 'posts/css/style.css' %}">
</head>
<body>
	<header>
		<div class="conteiner">
			<div class="header__inner">
				<div class="top_menu">
					<div class="logo">
						<a href="{% url 'posts:index' %}">Annihilator</a>
						<img width="35" src="{% static 'posts/img/logo.png' %}">
					</div>
					<form method="get" action="{% url 'posts:home_search' %}">
						<div class="search_conteiner">
							<div class="search_box">
								<input name="search_name" id="search_name_input" type="text" value="{{ product_name }}">
								<div class="search_list_conteiner" id="search_list_conteiner">
									<ul id="search_list">
									</ul>
								</div>
							</div>
							<button id="search_btn">
								<img width="60%" src="{% static 'posts/img/search-icon.png' %}">
							</button>
						</div>
					</form>
					{% if user.is_authenticated %}
					<div class="account__nav">
						<div class="nav_img_icon message_icon">
							<a href="{% url 'cart:requests_to_order' %}">
								<img width="30" src="{% static 'posts/img/mail-icon.png' %}">
							</a>
							<div class="count_text count_message">
								{{ request.new_messages_count }}
							</div>
						</div>
						<div class="nav_img_icon message_icon">
							<a href="{% url 'cart:cart' %}">
								<img width="30" src="{% static 'posts/img/cart.png' %}">
							</a>
							<div class="count_text count_message">
								{{ request.cart.get_total_quantity }}
							</div>
						</div>
						<a href="{% url 'accounts:logout' %}">Выход</a>
						<a href="{% url 'accounts:profile' user.username %}"><div style="height: 30px;
						width: 30px;background:url(
						{% if user.icon %}
							{{ user.icon.url }}
						{% else%}
							{% static 'posts/img/user-icon.png' %}
						{% endif %}) center;
						background-size: 100%;" class="profile_image"></div></a>
					</div>
					{% else %}
					<div class="account__nav">
						<a href="{% url 'accounts:login' %}">Войти</a>
						<a href="{% url 'accounts:register' %}">Регистрация</a>
					</div>
					{% endif %}
				</div>
				<div class="bottom_menu">
					<nav class="header__navigation">
						{% for rubric in rubrics %}
						<a href="{% url 'posts:rubrics' rubric.slug %}">{{ rubric }}</a>
						{% endfor %}
					</nav>
				</div>
			</div>
		</div>
	</header>
	<div class="messages" id="messages">
		<ul>
			{% for message in messages %}
			<li>{{ message }}</li>
			{% endfor %}
		</ul>
	</div>
	<main>
		<div class="conteiner">
			<div class="main__inner">
				{% block content %}
				{% endblock %}
			</div>
		</div>
	</main>
	<script src="{% static 'posts/js/script.js' %}"></script>
</body>
</html>

trudyagi/templates/base_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width">
    <title>Title</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Staatliches&family=Ubuntu:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet"  type="text/css" href="{% static 'posts/css/style.css' %}">
</head>
<body>
	<header>
		<div class="conteiner">
			<div class="header__inner">
				<div class="top_menu">
					<div class="logo">
						<a href="{% url 'posts:index' %}">Annihilator</a>
						<img width="35" src="{% static 'posts/img/logo.png' %}">
					</div>
					<form method="get" action="{% url 'posts:home_search' %}">
						<div class="search_conteiner">
							<div class="search_box">
								<input name="search_name" id="search_name_input" type="text" value="{{ product_name }}">
								<div class="search_list_conteiner" id="search_list_conteiner">
									<ul id="search_list">
									</ul>
								</div>
							</div>
							<button id="search_btn">
								<img width="60%" src="{% static 'posts/img/search-icon.png' %}">
							</button>
						</div>
					</form>
					{% if user.is_authenticated %}
					<div class="account__nav">
						<div class="nav_img_icon message_icon">
							<a href="{% url 'cart:requests_to_order' %}">
								<img width="30" src="{% static 'posts/img/mail-icon.png' %}">
							</a>
							<div class="count_text count_message">
								{{ request.new_messages_count }}
							</div>
						</div>
						<div class="nav_img_icon message_icon">
							<a href="{% url 'cart:cart' %}">
								<img width="30" src="{% static 'posts/img/cart.png' %}">
							</a>
							<div class="count_text count_message">
								{{ request.cart.get_total_quantity }}
							</div>
						</div>
						<a href="{% url 'accounts:logout' %}">Выход</a>
						<a href="{% url 'accounts:profile' user.username %}"><div style="height: 30px;
						width: 30px;background:url(
						{% if user.icon %}
							{{ user.icon.url }}
						{% else%}
							{% static 'posts/img/user-icon.png' %}
						{% endif %}) center;
						background-size: 100%;" class="profile_image"></div></a>
					</div>
					{% else %}
					<div class="account__nav">
						<a href="{% url 'accounts:login' %}">Войти</a>
						<a href="{% url 'accounts:register' %}">Регистрация</a>
					</div>
					{% endif %}
				</div>
			</div>
		</div>
	</header>
	<div class="messages" id="messages">
		<ul>
			{% for message in messages %}
			<li>{{ message }}</li>
			{% endfor %}
		</ul>
	</div>
	<main>
		<div class="conteiner">
			<div class="main__inner">
				{% block content %}
				{% endblock %}
				{% if page_obj %}
				<div class="paginator_list">
					{% if page_obj.has_previous %}
					<div class="paginator_item" data-page="{{ page_obj.previous_page_number }}">
						<span><</span>
					</div>

					<div class="paginator_item" data-page="1">
						<span>1</span>
					</div>
					<span>...</span>
					{% endif %}
					{% for page in page_obj.paginator.page_range %}
					{% if page >= page_obj.number|add:-1 and page <= page_obj.number|add:1 %}
					<div class="paginator_item" data-page="{{ page }}">
						<span>{{ page }}</span>
					</div>
<!--					<a href="?page={{ page }}">{{ page }}</a>-->
					{% endif %}
					{% endfor %}
					{% if page_obj.has_next %}
					<span>...</span>
					<div class="paginator_item" data-page="{{ page_obj.paginator.num_pages }}">
						<span>{{ page_obj.paginator.num_pages }}</span>
					</div>
					<div class="paginator_item" data-page="{{ page_obj.next_page_number }}">
						<span> > </span>
					</div>
					{% endif %}
				</div>
				{% endif %}
			</div>
		</div>
	</main>
	<script src="{% static 'posts/js/script.js' %}"></script>
	{% block scripts %}
	{% endblock %}
</body>
</html>