trudyagi/accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy, reverse

from . import views

app_name = 'accounts'

urlpatterns = [
    path('registration/', views.RegisterView.as_view(), name="register"),
    path('login/', views.LoginUserView.as_view(), name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('change_email/', views.change_email, name="change_email"),
    path('change_contact_email/', views.change_contact_email, name="change_contact_email"),
    path('change_password/', PasswordChangeView.as_view(template_name='accounts/change_password.html', success_url=reverse_lazy('posts:index')), name="change_password"),
    path('profile/<str:username>', views.profile_view, name='profile'),
    path('activation/user_key/<str:sign>', views.activation_user_view, name='activation_page'),
    path('activation/warning/<str:sign>', views.activation_warning_view, name='activation_warning'),
    path('activation/resend_activation/<str:sign>', views.resend_activation, name='resend_activation')
]

trudyagi/cart/urls.py
from django.urls import path, include
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('cart_add/<uuid:product_id>', views.cart_add, name='cart_add'),
    path('create_order/', views.send_order, name='create_order'),
    path('requests_to_order/', views.requests_to_order, name='requests_to_order'),
]

trudyagi/posts/urls.py
from django.urls import path, include
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('rubrics/<slug:rubric_slug>', views.get_by_rubric, name='rubrics'),
    path('product/<uuid:product_unique_id>', views.product, name='product_detail'),
    path('add_product/', views.CreateProductView.as_view(), name='add-product'),
    path('search-product-data/', views.search_product_data, name='search_product_data'),
    path('search/<slug:category_slug>/<str:product_name>/', views.search_product_page, name='search_product_page'),
    path('home_search/', views.search_product_home, name='home_search'),
    path('delete-review/<int:review_id>', views.delete_review, name='delete_review'),
    path('delete-product/<uuid:pk>', views.DeleteProductView.as_view(), name='delete_product'),
    path('update-product/<uuid:pk>', views.UpdateProductView.as_view(), name='update_product'),
]

trudyagi/trudyagi/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls', namespace='chat')),
    path('', include('posts.urls', namespace='posts')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('silk/', include('silk.urls', namespace='silk')),
    path('cart/', include('cart.urls', namespace='cart')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    path('static/', serve, {'document_root': settings.STATIC_ROOT})
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'trudyagi.views.handler404'
handler403 = 'trudyagi.views.handler403'
handler500 = 'trudyagi.views.handler500'

trudyagi/posts/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.views.generic import CreateView

from accounts.models import User
from .utils import slugify
from django.urls import reverse
import uuid

class Product(models.Model):
    PRODUCT_CONDITION_CHOICE = (
        ('n', 'Новый'),
        ('u', 'Б/у'),
    )
    SALE_TYPE_CHOICE  = (
        ('s', 'Продажа'),
        ('e', 'Обмен'),
        ('f', 'Даром')
    )

    id = models.UUIDField(primary_key=True, default=uuid.uuid4(), editable=False)
    name = models.CharField(max_length=70, verbose_name='Имя продукта')
    image = models.ImageField(upload_to='products-images/%Y/%m/%d', verbose_name='Изображение продукта')
    about = models.TextField(null=True, blank=True, verbose_name='О продукте')
    condition = models.CharField(max_length=5, default='n', choices=PRODUCT_CONDITION_CHOICE, verbose_name='Состояние товара')
    sale_type = models.CharField(max_length=5, default='s', choices=SALE_TYPE_CHOICE, verbose_name='Тип продажи')
    price = models.DecimalField(blank=True,default=0,max_digits=8,decimal_places=2, verbose_name='Цена')
    attributes = models.JSONField(null=True, blank=True,verbose_name='Характеристики')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор', related_name='products')
    category = models.ForeignKey('Category', null=True, on_delete=models.PROTECT, verbose_name='Категория', related_name='products')
    rating = models.FloatField(null=True, blank=True, verbose_name='Рейтинг', validators=[MaxValueValidator(5), MinValueValidator(0)])
    created = models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.sale_type in ['e', 'f']:
            self.price = 0
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:product_detail', args=[self.id])

    class Meta:
        ordering = ['-created']
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        indexes = [
            models.Index(fields=["attributes"]),
            models.Index(fields=["price"]),
            models.Index(fields=["name"]),
            models.Index(fields=["name","attributes"])
        ]

class Product_Image(models.Model):
    image = models.ImageField(upload_to='products-images/%Y/%m/%d')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Изображение продукта'
        verbose_name_plural = 'Изображения продуктов'

class Review(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Имя автора')
    content = models.TextField(verbose_name='Коомментарий')
    review = models.FloatField(verbose_name='Отзыв', validators=[MaxValueValidator(5), MinValueValidator(0)])
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='reviews')

    def save(self, commit=True, *args, **kwargs):
        if commit:
            author_comments = self.__class__.objects.filter(author=self.author, product=self.product)
        if author_comments:
            author_comments.delete()
        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Оценка'
        verbose_name_plural = 'Оценки'

class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название категории')
    slug = models.SlugField()
    rubric = models.ForeignKey('Rubric', on_delete=models.PROTECT, verbose_name='Рубрика', related_name='categories')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Rubric(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название рубрики')
    slug = models.SlugField()
    image = models.ImageField(upload_to='rubric-images/', verbose_name='Изображение рубрики')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Рубрика'
        verbose_name_plural = 'Рубрики'

trudyagi/posts/forms.py
from django import forms
from django.forms.renderers import get_default_renderer
from django.forms.utils import ErrorList
from django.utils.datastructures import MultiValueDict

from .models import Product, Review
from django.utils.text import slugify
from .attributes_conf import attributes_config
import copy
from django.utils.translation import gettext as _

class CreateProductForm(forms.ModelForm):
    price = forms.DecimalField(label='Цена',max_digits=8, decimal_places=2 ,required=False)
    images = forms.FileField(required=False, widget=forms.FileInput(attrs={'id':'images_input', 'multiple': True}))

    class Meta:
        model = Product
        exclude = ('author','slug','rating')
        widgets = {
            'image': forms.FileInput(attrs={'id': 'image_input'}),
            'price': forms.NumberInput(),
            'characteristics': forms.HiddenInput(),
        }

class CreateReviewForm(forms.ModelForm):
    review = forms.IntegerField(label='Оценка',max_value=5, widget=forms.NumberInput())
    class Meta:
        model = Review
        fields = ['review','content']

class FilterProductForm(forms.Form):
    PRODUCT_CONDITION_CHOICE = (
        ('n', 'Новый'),
        ('u', 'Б/у'),
    )
    SALE_TYPE_CHOICE = (
        ('s', 'Продажа'),
        ('e', 'Обмен'),
        ('f', 'Даром')
    )
    max_price = forms.IntegerField(required=False, max_value=99999999)
    min_price = forms.IntegerField(required=False, min_value=0)
    condition = forms.MultipleChoiceField(required=False,choices=PRODUCT_CONDITION_CHOICE, widget=forms.CheckboxSelectMultiple)
    sale_type = forms.MultipleChoiceField(required=False,choices=SALE_TYPE_CHOICE, widget=forms.CheckboxSelectMultiple)
    def __init__(self, category_name=None, *args, **kwargs):
        category_attrs = attributes_config.get(kwargs.get('category_name','list'), {})
        if kwargs.get('category_name'):
            del kwargs['category_name']
        super(FilterProductForm, self).__init__(*args, **kwargs)
        for name, value in category_attrs.items():
            self.fields[name] = value

    class Meta:
        fields = '__all__'

trudyagi/posts/views.py
import requests
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.edit import FormMixin
from .models import Rubric, Product, Product_Image, Review, Category
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView, FormView, DeleteView, UpdateView
from .forms import CreateProductForm, CreateReviewForm, FilterProductForm
from django.urls import reverse_lazy, reverse
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.template.loader import render_to_string
from cart.cart import Cart
from cart.forms import ProductAddInCartFrom
from django.contrib import messages
from django.shortcuts import redirect
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from decimal import Decimal
from .attributes_conf import attributes_config
from django.core.paginator import Paginator

def index(request):
    rubrics = Rubric.objects.all()
    products = Product.objects.all()[:10]
    return render(request, 'posts/index.html', {'rubrics': rubrics,
                                                'products':products})

class CreateProductView(LoginRequiredMixin, CreateView):
    form_class = CreateProductForm
    template_name = 'posts/create-product.html'

    def get_success_url(self):
        return reverse('posts:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rubrics'] = Rubric.objects.all()
        return context

    def form_valid(self, form):
        product = form.save(commit=False)
        product.author = self.request.user
        self.object = product.save()
        for image in self.request.FILES.getlist('images'):
            Product_Image.objects.create(product=product, image=image)
        return HttpResponseRedirect(self.get_success_url())

def get_by_rubric(request, rubric_slug):
    rubrics = Rubric.objects.all()
    rubric = Rubric.objects.get(slug=rubric_slug)
    products = Product.objects.filter(category__rubric=rubric)
    return render(request, 'posts/by_rubric.html', {'rubric':rubric,'rubrics':rubrics,'products': products})

def product(request, product_unique_id):
    product = get_object_or_404(Product.objects.prefetch_related('reviews' ,'reviews__author'), pk=product_unique_id)
    cart_form = ProductAddInCartFrom()

    if request.method == 'POST':
        form = CreateReviewForm(request.POST)
        if form.is_valid():
            errors = None
            if request.user:
                review = form.save(commit=False)
                review.author = request.user
                review.product = product
                review.save()
        return HttpResponseRedirect(reverse('posts:product_detail', args=[product_unique_id]))

    elif request.method == 'GET':
        rubrics = Rubric.objects.all()
        return render(request, 'posts/detail-product.html', {'rubrics':rubrics,'product':product,
                                                            'review_form': CreateReviewForm,
                                                            'cart_form':cart_form})

@csrf_exempt
def search_product_data(request):
    if request.method == 'POST':
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            search_products = Product.objects.filter(name__icontains=request.POST.get('search_data')).order_by('name').distinct('name')[:10]
            if search_products:
                return JsonResponse({'search_data': [prod.name for prod in search_products]})
            else:
                return JsonResponse({'search_data': False})
    else:
        return HttpResponseRedirect(reverse('posts:index'))

def search_product_home(request):
    if bool(request.GET.get('search_name')):
        return HttpResponseRedirect(reverse('posts:search_product_page', args=['list' ,request.GET.get('search_name')]))
    else:
        return redirect('posts:index')

def search_product_page(request, category_slug, product_name):
    search_params_list = {}
    main_category = False
    rubrics = Rubric.objects.prefetch_related('categories').all()
    page_number = request.GET.get('page', 1)
    products = None
    if category_slug == 'list':
        category = Category.objects.all()
        main_category = 'Все категории'
    else:
        category = (get_object_or_404(Category, slug=category_slug),)
        main_category = category[0].name
    if request.method == 'GET':
        filterForm = FilterProductForm(data=request.GET, category_name=main_category)
        if filterForm.is_valid():
            cd = filterForm.cleaned_data
            for attr_name in cd.keys():
                if attr_name not in filterForm.base_fields.keys():
                    value = cd.get(attr_name)
                    if value:
                        search_params_list[f'attributes__{attr_name}__in'] = value
            if product_name != 'empty':
                products = Product.objects.filter(
                    Q(name__icontains=product_name,
                      category__in=category,
                      price__gte=request.GET.get('min_price', 0),
                      price__lte=request.GET.get('max_price', 99999999),
                      condition__in=request.GET.getlist('condition', ['n', 'u']),
                      sale_type__in = request.GET.getlist('sale_type', ['s','e','f']),
                      **search_params_list))
            else:
                products = Product.objects.filter(
                    Q(category__in=category, **search_params_list))

            paginator = Paginator(products, 20)
            page_obj = paginator.get_page(page_number)
            return render(request, 'posts/search_product.html', {'rubrics': rubrics,
                                                                 'category_slug': category_slug,
                                                                 'category': main_category,
                                                                 'products': products,
                                                                 'form': filterForm,
                                                                 'product_name': product_name,
                                                                 'page_obj': page_obj
                                                                 })
        else:
            redirect('posts:index')

@csrf_exempt
def delete_review(request, review_id):
    review = Review.objects.select_related('author').get(pk=review_id)
    if review.author == request.user:
        review.delete()
        return JsonResponse({'action':'success_deleted'})

class DeleteProductView(DeleteView):
    model = Product
    success_url = reverse_lazy('posts:index')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.author == self.request.user:
            return super().post(request)
        else:
            raise PermissionDenied()

class UpdateProductView(UpdateView):
    model = Product
    form_class = CreateProductForm
    template_name = 'posts/update_product.html'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.author == self.request.user:
            return super().get(request, *args, **kwargs)
        else:
            raise PermissionDenied()

    def get_success_url(self):
        return reverse('posts:product_detail', args=[self.get_object().id])

    def form_valid(self, form):
        product = form.save(commit=False)
        product.author = self.request.user
        self.object = product.save()
        for image in self.request.FILES.getlist('images'):
            Product_Image.objects.create(product=product, image=image)
        return HttpResponseRedirect(self.get_success_url())

trudyagi/posts/templates/posts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width">
    <title>Title</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Staatliches&family=Ubuntu:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet"  type="text/css" href="{% static 'posts/css/style.css' %}">
</head>
<body>
	<header>
		<div class="conteiner">
			<div class="header__inner">
				<div class="top_menu">
					<div class="logo">
						<a href="{% url 'posts:index' %}">Annihilator</a>
						<img width="35" src="{% static 'posts/img/logo.png' %}">
					</div>
					<div class="search_conteiner">
						<div class="search_box">
							<input id="search_input" type="text">
							<div class="search_list_conteiner" id="search_list_conteiner">
								<ul id="search_list">
								</ul>
							</div>
						</div>
						<button id="search_btn">
							<img width="60%" src="{% static 'posts/img/search-icon.png' %}">
						</button>
					</div>
					{% if user.is_authenticated %}
					<div class="account__nav">
						<div class="nav_img_icon message_icon">
							<a href="{% url 'cart:requests_to_order' %}">
								<img width="30" src="{% static 'posts/img/mail-icon.png' %}">
							</a>
							<div class="count_text count_message">
								{{ request.new_messages_count }}
							</div>
						</div>
						<div class="nav_img_icon message_icon">
							<a href="{% url 'cart:cart' %}">
								<img width="30" src="{% static 'posts/img/cart.png' %}">
							</a>
							<div class="count_text count_message">
								{{ request.cart.get_total_quantity }}
							</div>
						</div>
						<a href="{% url 'accounts:logout' %}">Выход</a>
						<a href="{% url 'accounts:profile' user.username %}"><div style="height: 30px;
						width: 30px;background:url(
						{% if user.icon %}
							{{ user.icon.url }}
						{% else%}
							{% static 'posts/img/user-icon.png' %}
						{% endif %}) center;
						background-size: 100%;" class="profile_image"></div></a>
					</div>
					{% else %}
					<div class="account__nav">
						<a href="{% url 'accounts:login' %}">Войти</a>
						<a href="{% url 'accounts:register' %}">Регистрация</a>
					</div>
					{% endif %}
				</div>
				<div class="bottom_menu">
					<nav class="header__navigation">
						{% for rubric in rubrics %}
						<a href="{% url 'posts:rubrics' rubric.slug %}">{{ rubric }}</a>
						{% endfor %}
					</nav>
				</div>
			</div>
		</div>
	</header>
	<div class="messages" id="messages">
		<ul>
			{% for message in messages %}
			<li>{{ message }}</li>
			{% endfor %}
		</ul>
	</div>
	<main>
		<div class="conteiner">
			<div class="main__inner">
				{% block content %}
				{% endblock %}
			</div>
		</div>
	</main>
	<script src="{% static 'posts/js/script.js' %}"></script>
</body>
</html>

trudyagi/posts/templates/posts/by_rubric.html
{% extends 'base.html' %}

{% block content %}
<section class="section">
    <div class="name_section">
        <h2>{{ rubric.name }}</h2>
    </div>
    <div class="section_content">
        <div class="products_conteiner">
            {% for product in products %}
            <div class="product_icon">
                <div class="product_icon__content">
                    <a href="{{ product.get_absolute_url }}">
                        <div class="product_image_place">
                            <img class="convenient_picture" src="{{ product.image.url }}">
                        </div>
                        <div class="product_icon_name">
                            <span>{{ product.name }}</span>
                        </div>
                    </a>
                    <div class="product_icon_price">
                        {% if product.price %}
                            <b>{{ product.price }}$</b>
                        {% elif product.price == f %}
                            <b>Даром</b>
                        {% elif product.price == e %}
                            <b>Обмен</b>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

trudyagi/posts/templates/posts/create-product.html
{% extends 'base_detail.html' %}
{% load static %}

{% block content %}
<div class="create_product_conteiner">
    <div class="form_header">
        <h1>Добавить продукт</h1>
    </div>
    <form class="product_form" method="post" enctype="multipart/form-data">
        <h2>
            Изображение продукта:
        </h2>
        {% if form.errors %}
            <div class="form_error_list">
                {{ form.errors }}
            </div>
        {% endif %}
        <div class="product_add_image_conteiner">
            <div id="image_conteiner" class="product_add_image_content">
                <img id="product_image">
            </div>
        </div>
        {% csrf_token %}
        {{ form.as_table }}
        <br>
        <button class="blue_btn" type="submit" id="create_submit_btn">Добавить продукт</button>
    </form>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'posts/js/script_create_product.js' %}"></script>
{% endblock %}

trudyagi/posts/templates/posts/detail-product.html
{% extends 'base_detail.html' %}
{% load static %}

{% block content %}
{% if product.author == user %}
<div class="white_back_block">
    <h3>Изменение вашего товара:</h3>
    <form method="post" action="{% url 'posts:delete_product' product.id %}">
        {% csrf_token %}
        <button type="submit">Удалить</button>
    </form>
    <form method="get" action="{% url 'posts:update_product' product.id %}">
        {% csrf_token %}
        <button type="submit">Редактировать</button>
    </form>
</div>
{% endif %}
<div id="removal_question">
    <div class="question_content">
        <div class="question_text">
            Вы точно хотите удалить отзыв?
        </div>
        <div class="question_btns">
            <div class="blue_btn" id="question_review_delete_yes">
                Да
            </div>
            <div class="red_btn" id="question_review_delete_no">
                Нет
            </div>
        </div>
    </div>
</div>
<div class="product-detail">
    <div class="main_product_info">
        <div class="column_conteiner">
            <div class="product_any_info_conteiner">
                <div class="foto_slider_conteiner">
                    <div class="slider_canvas">
                        <button class="slider_button" id="left-slider-btn"><</button>
                        <button class="slider_button" id="right-slider-btn"> ></button>
                    </div>
                    <div class="foto_slider" id="foto-slider">
                        <div class="product_big_image">
                            <img class="convenient_picture"  src="{{ product.image.url }}">
                        </div>
                        {% for image in product.product_image_set.all %}
                        <div class="product_big_image">
                            <img class="convenient_picture" src="{{ image.image.url }}">
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="product_any_info_conteiner">
                <div class="product_info">
                    <span>Было выставлено: {{ product.created }}</span>
<!--                    <div class="product_rating">-->
<!--                        {% if product.rating %}-->
<!--                        <div class="star_rating">-->
<!--                            {{ product.rating }}-->
<!--                        </div>-->
<!--                        {% else %}-->
<!--                        <span class="no_ration">Нету оценок</span>-->
<!--                        {% endif %}-->
<!--                    </div>-->
                    <h2>{{ product.name }}</h2>
                    <h1>
                        {% if product.sale_type == 's' %}
                                {{ product.price }}$
                        {% elif product.sale_type == 'f' %}
                                Даром
                        {% elif product.sale_type == 'e' %}
                                Обмен
                        {% endif %}
                    </h1>
                    <hr>
                    <span>
                        Состояние:
                        {% if product.condition == n %}
                        Новое
                        {% else %}
                        Б/у
                        {% endif %}
                    </span>
                    <div class="product_about">
                        <p>{{ product.about }}</p>
                    </div>
                </div>
            </div>
            <div class="product_any_info_conteiner">
                <h2>Отзывы:</h2>
                <div class="create_review_conteiner">
                    <form class="review_form" id="review_form" method="post">
                        {% csrf_token %}
                        {{ review_form }}
                        <button type="submit" id="review_btn" class="blue_btn">Отправить отзыв</button>
                    </form>
                </div>
                <div class="reviews_conteiner">
                    <div class="reviews_list">
                        {% for review in product.reviews.all %}
                        <div class="review_view" {% if review.author == user %} id="this_author_review" {% endif %}>
                            <div class="review_author">
                                {{ review.author.first_name }} {{ review.author.last_name }}
                            </div>
                            <br>
                            Отзыв:
                            <div class="review_view_content">
                                <p>{{ review.content }}</p>
                            </div>
                            <div class="review_actions">
                                {% if review.author == user %}
                                <a class="delete_review_btn" data-delete_href="{% url 'posts:delete_review' review.pk %}">
                                    <img width="30" src="{% static 'posts/img/trash.png' %}">
                                </a>
                                {% endif %}
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="column_conteiner">
            <div class="product_any_info_conteiner">
                <div class="product_about_author">
                    <h3>Автор поста</h3>
                    <br>
                    <div class="product_author_main_info">
                        <a href="{% url 'accounts:profile' product.author.username %}">
                            <div class="product_author_main_info">
                                <div style="height: 50px;
                                    width: 50px;background:url(
                                    {% if product.author.icon %}
                                        {{ product.author.icon.url }}
                                    {% else%}
                                        {% static 'posts/img/user-icon.png' %}
                                    {% endif %}) center;
                                    background-size: 100%;" class="profile_image">
                                </div>
                                <div class="product_author_name">
                                    <h2>{{ product.author.first_name }} {{ product.author.last_name }}</h2>
                                </div>
                            </div>
                        </a>
                    </div>
                    <br>
                    <div class="author_contact_info">
                        Свяжитесь с продавцом:<br>
                        <b>{{ product.author.contacts }}</b>
                    </div>
                </div>
            </div>
            <div class="product_any_info_conteiner">
                <div class="buy_product_content">
                    <form action="{% url 'cart:cart_add' product.id %}" method="post">
                        {% csrf_token %}
                        {% if product.sale_type == 's' %}
                            {{ cart_form }}
                            <button class="blue_btn">Добавить в корзину</button>
                        {% elif product.sale_type == 'f' %}
                            <input type="hidden" name="id_quantity" value="1">
                            <button class="blue_btn">Добавить в корзину</button>
                        {% elif product.sale_type == 'e' %}
                            <input type="hidden" name="id_quantity" value="1">
                            <button class="blue_btn">Предложить обмен</button>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{{ product.rating|json_script:'product-rating-data' }}
{% endblock %}

{% block scripts %}
<script src="{% static 'posts/js/script_detail_product.js' %}"></script>
{% endblock %}