trudyagi/accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy, reverse

from . import views

app_name = 'accounts'

urlpatterns = [
    path('registration/', views.RegisterView.as_view(), name="register"),
    path('login/', views.LoginUserView.as_view(), name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('change_email/', views.change_email, name="change_email"),
    path('change_contact_email/', views.change_contact_email, name="change_contact_email"),
    path('change_password/', PasswordChangeView.as_view(template_name='accounts/change_password.html', success_url=reverse_lazy('posts:index')), name="change_password"),
    path('profile/<str:username>', views.profile_view, name='profile'),
    path('activation/user_key/<str:sign>', views.activation_user_view, name='activation_page'),
    path('activation/warning/<str:sign>', views.activation_warning_view, name='activation_warning'),
    path('activation/resend_activation/<str:sign>', views.resend_activation, name='resend_activation')
]

trudyagi/cart/urls.py
from django.urls import path, include
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('cart_add/<uuid:product_id>', views.cart_add, name='cart_add'),
    path('create_order/', views.send_order, name='create_order'),
    path('requests_to_order/', views.requests_to_order, name='requests_to_order'),
]

trudyagi/posts/urls.py
from django.urls import path, include
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('rubrics/<slug:rubric_slug>', views.get_by_rubric, name='rubrics'),
    path('product/<uuid:product_unique_id>', views.product, name='product_detail'),
    path('add_product/', views.CreateProductView.as_view(), name='add-product'),
    path('search-product-data/', views.search_product_data, name='search_product_data'),
    path('search/<slug:category_slug>/<str:product_name>/', views.search_product_page, name='search_product_page'),
    path('home_search/', views.search_product_home, name='home_search'),
    path('delete-review/<int:review_id>', views.delete_review, name='delete_review'),
    path('delete-product/<uuid:pk>', views.DeleteProductView.as_view(), name='delete_product'),
    path('update-product/<uuid:pk>', views.UpdateProductView.as_view(), name='update_product'),
]

trudyagi/trudyagi/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls', namespace='chat')),
    path('', include('posts.urls', namespace='posts')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('silk/', include('silk.urls', namespace='silk')),
    path('cart/', include('cart.urls', namespace='cart')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    path('static/', serve, {'document_root': settings.STATIC_ROOT})
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'trudyagi.views.handler404'
handler403 = 'trudyagi.views.handler403'
handler500 = 'trudyagi.views.handler500'

trudyagi/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    icon = models.ImageField(upload_to='profile-icons/', null=True, blank=True, verbose_name='Фото пользователя')
    about = models.TextField(null=True, blank=True, verbose_name='О себе')
    contacts = models.EmailField(null=True, blank=True, verbose_name='Контактный email')
    rating = models.FloatField(null=True, blank=True)

trudyagi/accounts/forms.py
from django.forms import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User
from .apps import register_signal

class RegistrationForm(UserCreationForm):

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.is_active = False
        if commit:
            user.save()
            print('Register')
        register_signal.send(RegistrationForm, instance=user)
        return user


    class Meta:
        model = User
        fields = ['username','first_name','last_name','icon', 'email', 'password1', 'password2']

trudyagi/accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.views.generic import CreateView
from django.http import JsonResponse, HttpResponseRedirect
from django.contrib.auth import login
from .models import User
from .forms import RegistrationForm
from django.contrib.auth.views import LoginView
from django.contrib.auth import logout
from django.urls import reverse_lazy, reverse
from django.shortcuts import redirect
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from .utilites import signer
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.mixins import LoginRequiredMixin
from .tasks import send_activation_email_task
from django.contrib.auth.decorators import login_required

class RegisterView(CreateView):
    form_class = RegistrationForm
    template_name = 'accounts/register.html'

    def form_valid(self, form):
        messages.add_message(self.request, messages.INFO , 'Вы успешно зерегестрировались! Теперь можете войти в аккаунт')
        self.object = form.save()
        return HttpResponseRedirect(reverse('accounts:activation_warning', args=[signer.sign(self.object.username)]))

class LoginUserView(LoginView):
    form_class = AuthenticationForm
    template_name = 'accounts/login.html'
    model = User
    success_url = reverse_lazy('posts:index')

    def form_valid(self, form):
        messages.add_message(self.request, messages.INFO , 'Вы вошли ваккаунт!')
        return super().form_valid(form)

def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('posts:index'))

def profile_view(request, username):
    user = User.objects.prefetch_related('products').get(username=username)
    return render(request, 'accounts/profile.html', {'profile_user':user})

def activation_user_view(request, sign):
    user = User.objects.get(username=signer.unsign(sign))
    user.is_active = True
    user.save()
    return render(request,'accounts/success_activation.html', {})

def activation_warning_view(request, sign):
    return render(request, 'accounts/activation_warning.html', {'sign':sign})

class ChangePasswordView(LoginRequiredMixin, PasswordChangeView):
    template_name = 'accounts/change_password.html'
    success_url = reverse_lazy('posts:index')

def resend_activation(request, sign):
    user = User.objects.get(username=signer.unsign(sign))
    send_activation_email_task.delay(user.email, user.username)
    return HttpResponseRedirect(reverse('accounts:activation_warning', args=[sign]))

@login_required
def change_email(request):
    errors = []
    if request.method == 'POST':
        print(request.POST.get('new_email'))
        request.user.email = request.POST.get('new_email')
        request.user.save()
        return redirect('posts:index')
    return render(request, 'accounts/change_email.html', {'errors':errors})

def change_contact_email(request):
    errors = []
    if request.method == 'POST':
        print(request.POST.get('new_email'))
        request.user.contacts = request.POST.get('new_email')
        request.user.save()
        return redirect('posts:index')
    return render(request, 'accounts/change_contact_email.html', {'errors':errors})

trudyagi/accounts/templates/accounts/activation_warning.html
{% extends 'base.html' %}

{% block content %}
<h1>Активируйся</h1>
<h3>Вам на электронную почту пришло сообщение об активации</h3>
<br>
<p>Вам не пришло сообщение? Отправьте повторное письмо</p>
<a href="{% url 'accounts:resend_activation' sign %}">Отправить повторно</a>
{% endblock %}

trudyagi/accounts/templates/accounts/change_contact_email.html
{% extends 'base_detail.html' %}

{% block content %}
<div class="page_form">
    <div class="page_form_tabs">
        <div class="form_header">
            <h1>Изменение контактный email</h1>
        </div>
        <div class="page_form_content">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <label>Новый email:</label><br><input name="new_email" type="email"><br>
                <button>Изменить email</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

trudyagi/accounts/templates/accounts/change_email.html
{% extends 'base_detail.html' %}

{% block content %}
<div class="page_form">
    <div class="page_form_tabs">
        <div class="form_header">
            <h1>Изменение email</h1>
        </div>
        <div class="page_form_content">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <label>Новый email:</label><br><input name="new_email" type="email"><br>
                <button>Изменить email</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

trudyagi/accounts/templates/accounts/change_password.html
{% extends 'base_detail.html' %}

{% block content %}
<div class="page_form">
    <div class="page_form_tabs">
        <div class="form_header">
            <h1>Изменение пароля</h1>
        </div>
        <div class="page_form_content">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for elem in form %}
                <label>{{ elem.label }}</label><br>
                {{ elem }}<br>
                {% endfor %}
                <button>Изменить пароль</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

trudyagi/accounts/templates/accounts/login.html
{% extends 'base_detail.html' %}

{% block content %}
<div class="page_form">
    <div class="page_form_tabs">
        <div class="auth_navigation">
            <div class="auth_tab">
                <a href="{% url 'accounts:register' %}">Регистрация</a>
            </div>
            <div class="auth_tab auth_tab_active">
                <a href="{% url 'accounts:login' %}">Вход</a>
            </div>
        </div>
        <div class="tab_content register_tab">
            <div class="form_header">
                <h1>Вход</h1>
            </div>
            <form id="register_form" method="post" enctype="multipart/form-data">
                {% if form.errors %}
                    <div class="form_error_list">
                        {{ form.errors }}
                    </div>
                {% endif %}
                {% csrf_token %}
                {% for item in form %}
                <label>{{ item.label }}</label><br>
                {{ item }}<br>
                {% endfor %}
                <button id="register_btn">Вход</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

trudyagi/accounts/templates/accounts/profile.html
{% extends 'base_detail.html' %}
{% load static %}

{% block content %}
<div class="profile_conteiner">
    <div class="profile_window">
        <div style="height: 150px;
            width: 150px;background:url(
            {% if profile_user.icon %}
               {{ profile_user.icon.url }}
            {% else %}
                {% static 'posts/img/user-icon.png' %}
            {% endif %}
            ) center;
            background-size: 100%;" class="profile_image">
        </div>
        <div class="profile_name">
            <h1>{{ profile_user.first_name }} {{ profile_user.last_name }}</h1>
        </div>
    </div>
</div>
{% if user == profile_user %}
<section class="section">
    <div class="name_section">
        <h2>Настройки</h2>
    </div>
    <div class="section_content">
        <div class="profile_settings">
            <div class="profile_settings_tab">
                <a href="{% url 'accounts:change_password' %}">Изменить пароль</a>
            </div>
            <div class="profile_settings_tab">
                <a href="{% url 'accounts:change_contact_email' %}">Изменить контактный email</a>
            </div>
            <div class="profile_settings_tab">
                <a href="{% url 'accounts:change_email' %}">Изменить email</a>
            </div>
        </div>
    </div>
</section>
{% endif %}
<section class="section">
    <div class="name_section">
        <h2>Объявления</h2>
    </div>
    <div class="section_content">
        {% if user == profile_user %}
        <div class="product_any_info_conteiner">
            <a href="{% url 'posts:add-product' %}" class="blue_btn">Добавить продукт</a>
        </div>
        {% endif %}
        <div class="products_conteiner">
            {% for product in profile_user.products.all %}
            <div class="product_icon">
                <div class="product_icon__content">
                    <a href="{{ product.get_absolute_url }}">
                        <div class="product_image_place">
                            <img class="convenient_picture" src="{{ product.image.url }}">
                        </div>
                        <div class="product_icon_name">
                            <span>{{ product.name }}</span>
                        </div>
                    </a>
                    <div class="product_icon_price">
                        <b>{{ product.price }}$</b>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

trudyagi/accounts/templates/accounts/register.html
{% extends 'base_detail.html' %}

{% block content %}
<div class="page_form">
    <div class="page_form_tabs">
        <div class="auth_navigation">
            <div class="auth_tab auth_tab_active">
                <a href="{% url 'accounts:register' %}">Регистрация</a>
            </div>
            <div class="auth_tab">
                <a href="{% url 'accounts:login' %}">Вход</a>
            </div>
        </div>
        <div class="tab_content register_tab">
            <div class="form_header">
                <h1>Регистрация</h1>
            </div>
            {% if form.errors %}
            <div class="form_error_list">
                {{ form.errors }}
            </div>
            {% endif %}
            <form id="register_form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for item in form %}
                <label>{{ item.label }}</label><br>
                {{ item }}<br>
                {% endfor %}
                <button id="register_btn">Зарегистрироваться</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

trudyagi/accounts/templates/accounts/success_activation.html
{% extends 'base_detail.html' %}

{% block content %}
<h1>Успешная активация!</h1>
<h3>Теперь вы можете <a href="{% url 'accounts:login' %}">Войти в аккаунт</a></h3>
{% endblock %}